version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/data
    environment:
      - EQUINOX_DB_PATH=/data/vault.db
      - EQUINOX_HEX_KEY=${EQUINOX_HEX_KEY}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 64M
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - whisper-engine
    networks:
      - equinox-net

  whisper-engine:
    build:
      context: ./docker/whisper
      dockerfile: Dockerfile
    volumes:
      - ./whisper_models/ggml-tiny.bin:/models/model.bin:ro
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 256M
    networks:
      - equinox-net
    restart: always


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:8080/api/v1
      - ORIGIN=http://localhost:3000
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - equinox-net

networks:
  equinox-net:
    driver: bridge
